temperature: 0.3
save: true
#model: "gpt-3.5-turbo"
#model: "gpt-4"
#model: openai:gpt-4-1106-preview
model: openai:gpt-4o
conversation_first: true

clients:
  - type: openai
    organization_id: org-W8FnqWxpWPEBzGoZtXfezrCw


